Abaynesh Getenet kebede
Abaynew Tibebu Geza
Abebaw Wudu Tsegaye
Abebe Demise Nebiyu
Abebe Shitaw Kume
Abebe Zelalem Mengstu
Abeje Alene Sharew
Abeju Tadesse  Mandefro
Abel Andargie kassa
Abenet Manaye Fetene
Abraham Asmelash Teferi
Abrham Taye Nigatu
Abubeker Yesa Yebrie
Abush Beletew Zewde
Abyu Siyum Akal
Adamkew Mitikie K/Mariam
Adamu Amsalu Yeshta
Adamu Bimrew Mengistu
Adamu Tagele Trfie
Adane Takele Hailu
AddisAlem Adugna Andarge
Addishiwote Amogne Mulu
Addisu Woldie Gebru
Agemase  Menegie Demoze
Agumas Haregu Aneley
Akelilu Mequanint Admasse
Alefe Tewabe Asmare
Alemnew Getie Alemu
Alemu Alebie Zerihun
Alemu Tena Wuletaw
Altaseb Dessalign Demeke
Amanual Mollalegn Alefe
Amare Genet Ambaye
Ambaw Getaneh Kibret
Amlakie Temesgen Sibhat
Amsalu Dagnew Kibiret
Amsalu Kassahun Tefera
Amsalu Tadesse Kassahun
Andinet Ejigu Simegn
Andualem Adane Derebe
Andualem Mezigebu Amare
Anebachew Tilahun Asaye
Anemaw Assaye Kassa
Animie Ayehu Abebe
Animut Aschale Belayneh
Animut Mulat Gedfew
Aragaw Jemal Mohammed
Asefa Ayana Dememe
Asefa Getachew Dagnewu
Ashagrie Abate Belete
Asmare Anmute Wodaje
Asnakew chanie sharew
Asrat Sendeku Chekol
Assefa Abebaw Taye
Assefa Dejen Baye
Assefa Hagos Abraha
Atsede Mekonen Workeneh
Awoke Kindalem Tebabale
Ayalew Demelie Negash
Ayalsew Demelash Gashu
Ayana Alemu Alene
Ayesheshim Tarekegn Nigusie
Aytolgn Abew Andargew
Azimeraw Belsti Melese
Azimeraw Molla Andualm
Azmeraw Yimer Agegnehu
Bantalem Yizengaw Fenta
Bantayehu Andargie Emiru
Bantayen Asres W/Giwergis
Bantie Sisay Feleke
Baye Fante Gerelu
Bayew Jenber Ademe
Belay Chanie Chekol
Belayneh Addis Asres
Belayneh Gashaw Melesew
Belayneh Yalew Mekonen
Belaynew Alemnew Ambaw
Belete Mulu Ambelu
Belete Tilahun Haylu
Belisti Amanu Chekol
Beniam Amlaku Ayalew
Berehan Abebaw Demissie
Berihun Demewoz Adane
Betelehem Nibret Admas
Biazen Sentie Fetene
Bihonegn Abeje Amera
Bihonegne Tesfa Dagnaw
Bihonegne Tsegaw Abate
Biniam Asmamaw Nigatu
Birhanu Andualem Yigezaw
Birhanu Tagele Beresew 
Birtukan Tefera Asnake
Biruk Semahegn Tamir
Bisrat Teshome Maru
Buzualem Ababel Wale
Chalachew Tadesse Demissie
Chekole Debash Asefaw
Chris jakulin
Dagim Getahun Miskir
Dagmawi Tsegaye Minda
Danaiel Beyene Getie
Dawit Abader Osman
Dawit Abraham Jemberie
Dawit Mekuria Berie
Debashe Lejaleme W/Rufaele
Debrework Beyene Siata
Degu Maru Andaregie
Demeke Keskes Reta
Demeke Lawayew Desta
Demelash Enyew Kasie
Demelash Kindie Asemagegne
Demelash Tadese Alehegne
Dereje Tekeba Fetene
Derso Dejen Dagnaw
Derso Gashaw Getu
Desale Belay Ali
Dires Endeshaw Hassen
Ejigayehu Amare Tegegne
Emagnaw Kassie Tagele
Emebet Nigatu Mulleta
Enawgaw Abate Bitew
Endeshaw Mebrat Teshal
Ephrem Assefa Ayalew
Equar Fentaye Yemanebirhan
Erkie Abate Mera
Essa Mohammed Yenus
Estibel Ayechew Yimer
Ewunetu Dejene Gelaye
Ewunetu Teshager Muche
Eyerus Alem Azene
Fiker Azene Shiferaw
Fiker Walle Taw
Fiker Yohannes Tadesse
Gashanew Tadese Ayele
Gashaw Chanie Gebeyehu
Gashaw Melese Asmir
Gashaw Wasie Adem
Gebeyaw Molla Mengistu
Gedefaw Abebe Taye
Geremew Awoke Mengestu
Getachew Nigatu Enyew
Getachew Taye Mekuria
Getachew Tizazu Kassie
Getachew Tsegaye Beyene
Getahun Alamneh Alemayehu
Getahun Asmamaw Mekonen
Getahun Asrat Melese
Getahun Degu Tegegne
Getahun Liyew Mulie
Getawey Wubante Gelaye
Getenet Dersie Bitew
Geteye Awoke Yalew
Getie Alebachew Admassu
Getnet Addis Messele
Getnet Aklog Legesse
Getnet Baye Kibret
Getnet Tadesse Bogale
Gezahign Aynalem Mengistu
Gietie Tilahun Beyene
Girma Mekonen Yimer
Giziealew Fenta Adam
Goshe Mossa Getu
Goytom W/Mariam G/Medihn
Gzachew Yohannes  Gebru
Habtam Mandie Damtie
Habtamnesh Agumas Mekonnen
Habtamu Abebel Dilnesa
Habtamu Anegagrie Zeleke
Habtamu Birhanie G/Eyesus
Habtamu Eshetu Muche
Habtamu Fekadie Tegegne
Habtamu Gizachew Negash
Habtamu Molla Adebabay
Habtamu Selesh Geremew
Habtamu Shegaw Tibebu
Habtamu Zinaye Fenta
Habte Wodue Tehye
Hailemariam Fentie Eseyneh
Hailemichael Zeleke Mekonnen
Henok Tarekegn Shiferie
Hiwot Tarekegn Bayeh
Hylemariam Tesfaneh Alemu
Jegnie Linger Amsalu
Kassahun Mengestu Fenta
Kassaw Tessafaw Yikinaw
Kefale Ayalew Adgeh
Kerebih Negash Lema
Ketema Mengistu Buayalew
Kibret Kebede Tasew
Kindu Meku Birhanu
Koyachew Geberie  Mitku
Linger Barkelign Temesgen
Liyuwork Tegegne Guadie
Maereg Amare Kahesay
Mamaru Talema Biable
Manadefro Alem Damtie
Maru Asnakew Felek
Masresha Tadele Bantie
Mayet Feleke Adugna
Meberatu Getaneh Tadele
Mehider Getnet Ejigu
Mekuanent Baye Kebede
Melaku Debero Eranko
Melaku Teshome Gebeye
Melese Anetenehe Alemie
Melese Belay Taddese
Melishew Dagne Derseh
Melkamu Liyeh Tiruneh
Melkie Mekuanent Yerdaw
Melkie Mengist Tegegne
Mengesha Liyu Emirie
Mengistu Dereje chanie
Mengstu Abate Belay
Mesafint Kassa Tarekegn
Meseret Amsalu Wondim
Meserete Tadie Nigusie
Mesetayite Melese Hiruy
Mesfin Gizachew Tadege
Mesganaw Tafere Asefa 
Minichel Ayneshet Ayalew
Misganaw Kindu Abeje
Misganaw Tilahun Belay
Misganaw Yigizaw Ambaw
Misganew Alemneh Tirunhe
Mitiku Amera Dersie
Mossye Mekonnen Mekebeb
Motbaynor Muche Negash
Mulualem Maseresha Tilahun
Mulugeta Alamrew Yigzaw
Mulugeta Temesgen Gashu
Muluken Desalegne Gugssa
Muluken Mequanint Tegegne
Muluken Yihalem Fentie
Muluken Zelke Gualie
Muluye Chanie Tsega
Nardos Habtie Somega
Negestate Woletaw Mekoyia
Netsanet Minale Bayeh
Nigus Jember Mihretu
Nigussie Kerie Chekole
Ousman Jibril Endrise 
Seblework Ayalew Mitiku
Selabat Asnakew Asmare
Selomon G/Michael G/Hiwot
Selomon Yihun Kelemie
Sewagegn Terefe Admasu
Shashitu Aragaw Gessese
Silabat Dagnewu Wendalem
Silenat Workneh Abtew
Simegnew Zeleke Lakachew
Sisay Adisu Bogale
Sisay Ambaw Adugna
Sisay G/tsadik Haile
Sisay Tefera yasin
Sisaye Desalew Belay
Solomon Birhanie Wassie
Solomon Melak Alemu
Sosina Misganaw Dagnaw
Sultan Jibril Mohammed
Taddel Desta Zemo
Taddess Gizachew Engeda
Tadele Mekonnen Tareke
Tadese Alemu Tiruye
Tadese Nega Mengestie
Tadesse Tegegne Alemu
Takele Mulat Bihon
Tantigegn Anagaw Desta
Tayu Geberetsadik Damtew
Tazebew Girma Diress
Tebebu Negussie Cherenete
Temesgen Bizualem Yazie
Tenagne Beadege Bekele
Tenaw Belete Ejigu
Tesfa Ayalew Mekonnen
Tesfa Mengist Wondie
Tesfaye Gashaw Assaye
Tesfaye Mekonnen Wendimu
Tesfaye Zewdu Fentahun
Tewodros Hussien Gurmu
Tewodros Sinte Fetene
Tiruken Zeleke Atanaw
Tsedale  Dagnaw Abetew
Wagaye Mezegebu Gesses
Walelegne Tefera Hailie
Walelegne Zerfu Abate
Werkinesh Tirfie Sintayehu
Woldegiorgis Girmaw Getahun
Wolela Endalamaw Kassie
Workineh Meseret Ayalew
Worku Belete Gebeyehu
Worku Dessalegn Beadiglign
Wubalem Yimam Yirga
Wubet Adgo Sereche
Yalem Tadese Tesfaye
Yared Admasu Hailie
Yeabsira Balew Alameraw
Yebeltal Berhanu Fentie
Yeshambel Matebie Berie
Yeshiwas  Amlaku Geremew
Yibeltal Amisew Tizazu
Yibeltal Dessie Kasa
Yibeltal Menan kemal
Yihun Mengiste Bizuneh
Yihunie Bantie Ayele
Yishalale Abera Ayou
Yitref Ayele Wagaw
Yizanu Abeje Delele
Yohannes kassa Belete
Yohannes Tekle Najji
Yosef Fetene Lakew
Yosief Amare Alemu
Zekareyase Gebeyehue Mhiretu
Zelalem Amlaku Ayalew
Zelalem Guadu Mengistu
Zelalem Nibret Tesera
Zemene Minale Asres
Zemenu Alamrew Amogne
Zemenu Tamir Endalew
Zemenu Walelign Bishaw
Zemenu Wubet Chekol
Zena Mekonnen Aynalem
Zenebe Worku Beyene
Zerihun Gessese Hailu
Zewdu Chalachew Gashu